=begin
<PBXDom API>

OpenAPI spec version: 2.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instact of DefaultApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DefaultApi)
    end
  end

  # unit tests for calls_get
  # 
  # Gets &#x60;Calls&#x60; info. 
  # @param rpt_type Report type. (0 report, 1 widget, 2 chart).
  # @param rpt_id Report id.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :start Start offset.
  # @option opts [Float] :limit Number of results to return. Max 10K.
  # @option opts [String] :sort_by Sort column.
  # @option opts [String] :sort_type Sort mode asc/desc.
  # @option opts [String] :from_date Start date time.
  # @option opts [String] :to_date End date time.
  # @option opts [Float] :duration Duration range.
  # @option opts [String] :phone List of caller phone.
  # @option opts [String] :phone1 List of dialled phones.
  # @option opts [String] :co List of trunk/co.
  # @option opts [String] :ext list of extensions.
  # @option opts [Float] :pbx_id list of PBX Ids.
  # @option opts [Float] :call_source list of callsource.
  # @option opts [Float] :call_type list of call type signatures.(5 Unanswered Calls, 7 Transfered Calls, 8 Forwarded Calls)
  # @option opts [Float] :direction list of direction.(0 incoming, 1 outgoing, 2 internal)
  # @option opts [String] :caller_name list of caller name.
  # @option opts [String] :did list of did.
  # @option opts [String] :dnis list of dnis.
  # @option opts [String] :acc list of account code.
  # @option opts [Float] :ring Ring range.Seconds unit.
  # @option opts [Float] :cost Cost range.
  # @option opts [Float] :group Department/Group id.
  # @return [Array<InlineResponse200>]
  describe 'calls_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for features_charts_get
  # 
  # Gets &#x60;Charts&#x60; list. 
  # @param [Hash] opts the optional parameters
  # @return [Array<InlineResponse200>]
  describe 'features_charts_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for features_reports_get
  # 
  # Gets &#x60;Reports&#x60; list. 
  # @param [Hash] opts the optional parameters
  # @return [Array<InlineResponse200>]
  describe 'features_reports_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for features_widget_get
  # 
  # Gets &#x60;Widgets&#x60; list. 
  # @param [Hash] opts the optional parameters
  # @return [Array<InlineResponse200>]
  describe 'features_widget_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
